/**
 * Load YAML rules and write a browser-safe generated TypeScript catalog.
 * Run: npm run build-catalog -w @stackrail-io/aprf-engine
 *
 * `generatedAt` is a content hash (not wall-clock) so CI drift checks stay stable
 * when rule bodies are unchanged.
 */
import { createHash } from "crypto";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { loadRulesFromDisk, rulesRootDir } from "../src/loader";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "generated", "catalog.ts");

function contentStamp(categories: unknown, rules: unknown): string {
  const digest = createHash("sha256")
    .update(JSON.stringify({ categories, rules }))
    .digest("hex");
  return `sha256:${digest}`;
}

function main() {
  const root = rulesRootDir();
  const { rules, categories, errors } = loadRulesFromDisk(root);

  if (errors.length > 0) {
    console.error("aprf-engine build-catalog refused — validation errors:");
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const catalog = {
    generatedAt: contentStamp(categories, rules),
    ruleCount: rules.length,
    categories,
    rules,
  };

  const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-catalog.ts — do not edit by hand.
 * Source: packages/aprf-engine/rules/
 */
import type { GeneratedCatalog } from "../catalog-types.js";

export const GENERATED_CATALOG: GeneratedCatalog = ${JSON.stringify(catalog, null, 2)} as GeneratedCatalog;
`;

  if (existsSync(outPath)) {
    const prev = readFileSync(outPath, "utf8");
    if (prev === body) {
      console.log(`Unchanged ${outPath} (${rules.length} rules)`);
      return;
    }
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  console.log(`Wrote ${outPath} (${rules.length} rules, ${catalog.generatedAt})`);
}

main();
