/**
 * Load YAML rules and write a browser-safe generated TypeScript catalog.
 * Run: npm run build-catalog -w @stackrail-io/aprf-engine
 *
 * `generatedAt` is a content hash (not wall-clock) so CI drift checks stay stable
 * when rule bodies are unchanged.
 */
import { createHash } from "crypto";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { parse as parseYaml } from "yaml";
import type { CrosswalkDef, GeneratedCatalog, ThreatIntelDef } from "../src/catalog-types";
import { loadRulesFromDisk, rulesRootDir } from "../src/loader";
import { collectSignalIds, type Indicator } from "../src/threat-composition";
import { validateAllByDomainYaml } from "./validate-catalog";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "generated", "catalog.ts");
const evidenceTypeIdsOutPath = join(
  here,
  "..",
  "src",
  "generated",
  "evidence-type-ids.ts",
);

/** Embed starter registry IDs so yaml-lint ships offline with the package. */
function loadEvidenceTypeIds(repoRoot: string): string[] {
  const path = join(repoRoot, "spec", "evidence-types.yaml");
  if (!existsSync(path)) return [];
  const doc = parseYaml(readFileSync(path, "utf8")) as {
    types?: Array<{ id?: string }>;
  };
  const ids = (doc.types ?? [])
    .map((t) => t.id)
    .filter((id): id is string => typeof id === "string" && id.length > 0);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length > 0) {
    throw new Error(
      `spec/evidence-types.yaml duplicate type id(s): ${[...new Set(dupes)].join(", ")}`,
    );
  }
  return ids;
}

function writeEvidenceTypeIds(ids: string[]): boolean {
  const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-catalog.ts — do not edit by hand.
 * Source: spec/evidence-types.yaml
 */
export const KNOWN_EVIDENCE_TYPE_IDS = ${JSON.stringify(ids, null, 2)} as const;
`;
  if (existsSync(evidenceTypeIdsOutPath)) {
    const prev = readFileSync(evidenceTypeIdsOutPath, "utf8");
    if (prev === body) return false;
  }
  mkdirSync(dirname(evidenceTypeIdsOutPath), { recursive: true });
  writeFileSync(evidenceTypeIdsOutPath, body);
  return true;
}

function contentStamp(
  domains: unknown,
  pillars: unknown,
  categories: unknown,
  rules: unknown,
  crosswalks: unknown,
  threatIntel: unknown,
  signalRegistry: unknown,
  threatComposition: unknown,
): string {
  const digest = createHash("sha256")
    .update(
      JSON.stringify({
        domains,
        pillars,
        categories,
        rules,
        crosswalks,
        threatIntel,
        signalRegistry,
        threatComposition,
      }),
    )
    .digest("hex");
  return `sha256:${digest}`;
}

function findRepoRoot(from: string): string {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "spec", "aprf-spec.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return from;
}

/** Crosswalks are published in spec/aprf-spec.json; embed them so the catalog ships offline. */
function loadCrosswalks(rulesRoot: string): CrosswalkDef[] {
  const specPath = join(findRepoRoot(rulesRoot), "spec", "aprf-spec.json");
  if (!existsSync(specPath)) return [];
  const spec = JSON.parse(readFileSync(specPath, "utf8")) as {
    crosswalks?: CrosswalkDef[];
  };
  return spec.crosswalks ?? [];
}

/** Threat context lives in spec/aprf-threat-map.yaml; embed it so the catalog ships offline. */
function loadThreatIntel(rulesRoot: string): Record<string, ThreatIntelDef> {
  const mapPath = join(findRepoRoot(rulesRoot), "spec", "aprf-threat-map.yaml");
  if (!existsSync(mapPath)) return {};
  const doc = parseYaml(readFileSync(mapPath, "utf8")) as {
    rules?: Record<string, ThreatIntelDef>;
  };
  return doc.rules ?? {};
}

function loadSignalRegistry(repoRoot: string): GeneratedCatalog["signalRegistry"] {
  const path = join(repoRoot, "spec", "aprf-signal-registry.yaml");
  if (!existsSync(path)) return undefined;
  const doc = parseYaml(readFileSync(path, "utf8")) as {
    version?: string;
    kinds?: GeneratedCatalog["signalRegistry"] extends infer S
      ? S extends { kinds: infer K }
        ? K
        : never
      : never;
    signals?: NonNullable<GeneratedCatalog["signalRegistry"]>["signals"];
  };
  if (!doc.version || !doc.kinds || !doc.signals) {
    throw new Error("spec/aprf-signal-registry.yaml incomplete");
  }
  const ids = doc.signals.map((s) => s.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length > 0) {
    throw new Error(
      `spec/aprf-signal-registry.yaml duplicate signal id(s): ${[...new Set(dupes)].join(", ")}`,
    );
  }
  return {
    version: doc.version,
    kinds: doc.kinds,
    signals: doc.signals,
  };
}

function loadThreatComposition(repoRoot: string): {
  threats: NonNullable<GeneratedCatalog["threatComposition"]>;
  checkThreatIndex: Record<string, string[]>;
} | null {
  const path = join(repoRoot, "spec", "aprf-threat-composition.yaml");
  if (!existsSync(path)) return null;
  const doc = parseYaml(readFileSync(path, "utf8")) as {
    threats?: NonNullable<GeneratedCatalog["threatComposition"]>;
  };
  const threats = doc.threats ?? {};
  const checkThreatIndex: Record<string, string[]> = {};
  for (const [threatId, body] of Object.entries(threats)) {
    for (const m of body.mitigations ?? []) {
      const list = checkThreatIndex[m.checkId] ?? [];
      if (!list.includes(threatId)) list.push(threatId);
      checkThreatIndex[m.checkId] = list;
    }
  }
  for (const id of Object.keys(checkThreatIndex)) {
    checkThreatIndex[id].sort((a, b) => a.localeCompare(b));
  }
  return { threats, checkThreatIndex };
}

function main() {
  const root = rulesRootDir();
  const catalogValidation = validateAllByDomainYaml(root);
  if (catalogValidation.errors.length > 0) {
    console.error(
      `aprf-engine build-catalog refused — ${catalogValidation.errors.length} YAML lint / path / spec mapping error(s):`,
    );
    for (const e of catalogValidation.errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const { rules, domains, pillars, categories, errors } = loadRulesFromDisk(root);

  if (errors.length > 0) {
    console.error("aprf-engine build-catalog refused — validation errors:");
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const crosswalks = loadCrosswalks(root);
  const ruleIds = new Set(rules.map((r) => r.id));
  const allPeerControlIds = new Set<string>();
  for (const cw of crosswalks) {
    for (const c of cw.controls ?? []) allPeerControlIds.add(c.id);
  }
  const danglingRelated: string[] = [];
  const crosswalkErrors: string[] = [];
  for (const cw of crosswalks) {
    const peerControlIds = new Set((cw.controls ?? []).map((c) => c.id));
    const mappedPeerIds = new Set<string>();
    for (const c of cw.controls ?? []) {
      for (const relatedId of c.relatedPeerControlIds ?? []) {
        if (!allPeerControlIds.has(relatedId)) {
          danglingRelated.push(`${cw.id} / ${c.id} → ${relatedId}`);
        }
      }
    }
    for (const m of cw.mappings ?? []) {
      // buildCrosswalkIndex skips mappings whose peer control is unknown, so an
      // unvalidated typo would silently drop crosswalks from reports.
      if (!peerControlIds.has(m.peerControlId)) {
        crosswalkErrors.push(
          `${cw.id} maps unknown peer control ${m.peerControlId}`,
        );
      }
      mappedPeerIds.add(m.peerControlId);
      for (const id of m.aprfCheckIds ?? []) {
        if (!ruleIds.has(id)) {
          crosswalkErrors.push(`${cw.id} maps unknown Check ${id}`);
        }
      }
    }
    // Every published peer control must have a mapping row or it never appears
    // on Checks / REPORT.html despite shipping in the catalog.
    const unmapped = [...peerControlIds].filter((id) => !mappedPeerIds.has(id));
    if (unmapped.length > 0) {
      crosswalkErrors.push(
        `${cw.id} has ${unmapped.length} control(s) with no mappings: ${unmapped.join(", ")}`,
      );
    }
  }
  if (danglingRelated.length > 0) {
    console.error(
      `aprf-engine build-catalog refused — ${danglingRelated.length} relatedPeerControlIds reference unknown peer controls:`,
    );
    for (const d of danglingRelated) console.error(`  - ${d}`);
    process.exit(1);
  }
  if (crosswalkErrors.length > 0) {
    console.error(
      `aprf-engine build-catalog refused — ${crosswalkErrors.length} crosswalk error(s):`,
    );
    for (const e of crosswalkErrors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const threatIntel = loadThreatIntel(root);
  for (const id of Object.keys(threatIntel)) {
    if (!ruleIds.has(id)) {
      console.error(
        `aprf-engine build-catalog refused — threat map describes unknown Check ${id}`,
      );
      process.exit(1);
    }
  }
  // Once the map exists it must stay complete, so a new Check cannot ship without
  // threat context. An absent map is tolerated for bootstrap builds.
  if (Object.keys(threatIntel).length > 0) {
    const missing = rules.map((r) => r.id).filter((id) => !threatIntel[id]);
    if (missing.length > 0) {
      console.error(
        `aprf-engine build-catalog refused — threat map missing ${missing.length} Check(s): ${missing.join(", ")}`,
      );
      process.exit(1);
    }
  }

  const repoRoot = findRepoRoot(root);
  const evidenceTypeIds = loadEvidenceTypeIds(repoRoot);
  if (evidenceTypeIds.length === 0) {
    console.error(
      "aprf-engine build-catalog refused — spec/evidence-types.yaml missing or empty",
    );
    process.exit(1);
  }
  const wroteEvidenceIds = writeEvidenceTypeIds(evidenceTypeIds);

  let signalRegistry: GeneratedCatalog["signalRegistry"];
  let threatComposition: GeneratedCatalog["threatComposition"];
  let checkThreatIndex: GeneratedCatalog["checkThreatIndex"];
  try {
    signalRegistry = loadSignalRegistry(repoRoot);
    const composition = loadThreatComposition(repoRoot);
    if (composition) {
      threatComposition = composition.threats;
      checkThreatIndex = composition.checkThreatIndex;
      if (!signalRegistry?.signals?.length) {
        console.error(
          "aprf-engine build-catalog refused — threat composition present but signal registry empty",
        );
        process.exit(1);
      }
      const knownSignals = new Set(signalRegistry.signals.map((s) => s.id));
      for (const [tid, body] of Object.entries(threatComposition)) {
        for (const m of body.mitigations) {
          if (!ruleIds.has(m.checkId)) {
            console.error(
              `aprf-engine build-catalog refused — threat ${tid} cites unknown Check ${m.checkId}`,
            );
            process.exit(1);
          }
        }
        const referenced = new Set<string>();
        for (const ind of body.indicators as Indicator[]) {
          collectSignalIds(ind, referenced);
        }
        for (const sid of referenced) {
          if (!knownSignals.has(sid)) {
            console.error(
              `aprf-engine build-catalog refused — threat ${tid} references unknown signal ${sid}`,
            );
            process.exit(1);
          }
        }
      }
    }
  } catch (e) {
    console.error(
      `aprf-engine build-catalog refused — signal/threat composition load failed: ${
        e instanceof Error ? e.message : String(e)
      }`,
    );
    process.exit(1);
  }

  const catalog = {
    generatedAt: contentStamp(
      domains,
      pillars,
      categories,
      rules,
      crosswalks,
      threatIntel,
      signalRegistry,
      threatComposition,
    ),
    ruleCount: rules.length,
    domains,
    pillars,
    categories,
    rules,
    crosswalks,
    threatIntel,
    ...(signalRegistry ? { signalRegistry } : {}),
    ...(threatComposition ? { threatComposition } : {}),
    ...(checkThreatIndex ? { checkThreatIndex } : {}),
  };

  const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-catalog.ts — do not edit by hand.
 * Source: packages/aprf-engine/rules/
 */
import type { GeneratedCatalog } from "../catalog-types.js";

export const GENERATED_CATALOG: GeneratedCatalog = ${JSON.stringify(catalog, null, 2)} as GeneratedCatalog;
`;

  let wroteCatalog = true;
  if (existsSync(outPath)) {
    const prev = readFileSync(outPath, "utf8");
    if (prev === body) wroteCatalog = false;
  }

  if (wroteCatalog) {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, body);
    console.log(`Wrote ${outPath} (${rules.length} rules, ${catalog.generatedAt})`);
  } else {
    console.log(`Unchanged ${outPath} (${rules.length} rules)`);
  }
  if (wroteEvidenceIds) {
    console.log(
      `Wrote ${evidenceTypeIdsOutPath} (${evidenceTypeIds.length} evidence types)`,
    );
  } else {
    console.log(
      `Unchanged ${evidenceTypeIdsOutPath} (${evidenceTypeIds.length} evidence types)`,
    );
  }
}

main();
